### PR TITLE
Fix leaks from manual JNI string conversions

### PR DESCRIPTION
**Pull request by kstenerud**
## Goal

The invalid UTF-8 C# to Java conversion crash fix involved manually creating Java native strings, which were leaking. This PR ensures they get cleaned up.

## Testing

Ran repro case manually (create tons of breadcrumbs on multiple threads) before and after changes to verify the fix.

### CODE REVIEW

**Review by fractalwrench — CHANGES_REQUESTED** [review]
This will reintroduce a unicode encoding crash that was fixed in #165 (also https://github.com/bugsnag/bugsnag-android/pull/584). The solution to this problem needs to call `BuildJavaStringDisposable`, invoke the JNI method, and then dispose of the object.

**Comment by kstenerud** [comment]
In that case, shouldn't we also fix the other CallNativeXYZ methods? They just pass the args directly as well...

**Comment by fractalwrench** [comment]
It'd be worth checking the methods again but in practice I don't think they're affected as they don't pass in user-submitted args.

**Review by fractalwrench — APPROVED** [review]
LGTM assuming this has been retested and the crash no longer occurs

**Comment by kstenerud** [comment]
Yup, tested with Abigail's repro case project.

**Pull request merged**
